---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # Must be manually updated each re-deployment
    server: 10.43.215.17
    path: "/"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: Secret
stringData:
  adminpassword: adminpassword
  passwords: password
  users: jovyan
  group: users
metadata:
  name: openldap
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  type: ClusterIP
  ports:
    - name: tcp-ldap
      port: 1389
      targetPort: tcp-ldap
  selector:
    app.kubernetes.io/name: openldap
---
apiVersion: v1
kind: Service
metadata:
  name: login
  labels:
    app.kubernetes.io/name: scheduler
spec:
  selector:
    app.kubernetes.io/name: scheduler
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: mpi
spec:
  selector:
    type: mpi-agent
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-login-private
data:
  munge.key: |
    yHelWKdI3uj9uQvFSlcvVbFgF43Jj6i/TM+J/ePHBVZcgmUbKfEYzbJU8MT4gzIgZjzZQF84TX3F
    gmdiLsuqQIpdvUMq6ydJRna2JU9TidDYw4tlzk1Evn03A0Br3spO42upWyIkDVAJyIu+Ehq+5o7H
    yHvBfTbNgJz+5BbRnKKMECC2mqVt3E+iWe6JdZbdlu4lhgSjPcAVJOoogW4nRpa8etSKEcnx4FCq
    y2t2WLGiMz2KxOZr86I7nuiIPuxITZzgbAJA6p8wJErl3ERiKililCBMVbADTQFD+bj4exNtqe+T
    JhgW3IFfUTGDb3zTmBsPD3wR1F7ulNUEZjA73P5VP9pVoMIJo9P4js7xPAvguYgiQXY1JPhkTMk6
    Cuo/yZzmgmu6yNq/WL2nf/iNVIhG0P2ai+s+S8RIfHO940unTWb4908OTYgaJbZrP0sDL1nmESrH
    oQMg/Ry9lbK47qG9mvjmOW3HuvSqxwLJD9baD7/UTNcsiqmf6YbG+FZ30uWN6eTV6u2QVGwUq3em
    SF6qPuZK+pVlV4WtAnoutJYNSw//7QWrMFWpHqioJ2kRE/Gkt6y0aY6Fqs4bjhr+BL7WUbKyOBcd
    ML+y+ZKcooeQDbU+8w+M6IUYeNp27/LVjAkTYGeYY17AHtqx0LcKuMosZi8ehaHuM6dnPWUoDgMF
    MEj416n8VeeAiQu4s2hYD2GdBLJNkUEosKPZ1AQOyOtqk9dNlyi42ynCOUmZdJNsZD2kz36OuDu+
    Bnfa/9rjs/ZS5bHE2o/EusV67GVE+MGLrMGcJoG6ewyta2F8HsDiRcncgUKn02Of6g3L75vwJUGU
    W0PHUPdg+POWliFSFKnMFeOf7ql6Slmdo1nbHpfZ3iyfkc0gVbYnQKRINHvKk/2mX77qes8m6HH+
    ILjIuuWxIYZ9uu/wU1xWj85sPgvGjRye9tziqCm9TgVksLWQc22jdGiktA92QpBlumjg0mfXWli0
    QOb7PATKZvAKKPn5N6Q5jiyI1hlDXKHzLz1EeoOGGSZ9KVFMj9u22MSTve83JiCID3DntFBzofax
    dR8CuVWuM0JSXaIe3ZKA/1gwQVyhcZwfyQhCU02HfBuXRzmasK42N8SfPwJ9AvSKALdnOLkD3vCX
    pNfsoDqxgugsCm0C6Vx/t4MeCX56nCUqRiliL1hgHb9I0RXvVw0/RRxS1b9zdpN7my/70A/HC3y6
    f/4zxxoPRSggPkIJStTMNJnk41awE52UZr549FoVdhOUKyo0EHqKaYprQLsaBRJENdtDq80jNnca
    bVvO3osSscXx8+7ixCtxKGwU7KbUh2nOB1K5Y2sEFUwg8KIdfbZN0O0udBhmJSvEl3kVjykgUw==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-login-public
data:
  slurm.conf: |
    # slurm.conf file generated by configurator easy.html.
    # Put this file on all nodes of your cluster.
    # See the slurm.conf man page for more information.
    #
    SlurmctldHost=scheduler
    #
    #MailProg=/bin/mail
    MpiDefault=none
    #MpiParams=ports=#-#
    ProctrackType=proctrack/cgroup
    ReturnToService=1
    SlurmctldPidFile=/run/slurmctld.pid
    #SlurmctldPort=6817
    SlurmdPidFile=/run/slurmd.pid
    #SlurmdPort=6818
    SlurmdSpoolDir=/var/lib/slurm-llnl/slurmd
    SlurmUser=slurm
    #SlurmdUser=root
    StateSaveLocation=/var/lib/slurm-llnl/slurmctld
    SwitchType=switch/none
    TaskPlugin=task/cgroup
    #
    #
    # TIMERS
    #KillWait=30
    #MinJobAge=300
    #SlurmctldTimeout=120
    #SlurmdTimeout=300
    #
    #
    # SCHEDULING
    FastSchedule=1
    SchedulerType=sched/backfill
    SelectType=select/cons_res
    SelectTypeParameters=CR_Core
    #
    #
    # LOGGING AND ACCOUNTING
    AccountingStorageType=accounting_storage/none
    ClusterName=cluster
    #JobAcctGatherFrequency=30
    JobAcctGatherType=jobacct_gather/none
    #SlurmctldDebug=info
    SlurmctldLogFile=/var/log/slurm-llnl/slurmctld.log
    #SlurmdDebug=info
    SlurmdLogFile=/var/log/slurm-llnl/slurmd.log
    #
    #
    # COMPUTE NODES
    # You should update this to match your cluster/node topology
    NodeName=agent-[0-3] Sockets=1 CoresPerSocket=8 ThreadsPerCore=1 State=UNKNOWN
    PartitionName=batch Nodes=agent-[0-3] Default=YES MaxTime=10080 State=UP
  cgroup.conf: |
    CgroupAutomount=yes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
        - name: openldap
          image: docker.io/bitnami/openldap:2
          imagePullPolicy: "Always"
          env:
            - name: LDAP_ADMIN_USERNAME
              value: "admin"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: adminpassword
                  name: openldap
            - name: LDAP_USERS
              valueFrom:
                secretKeyRef:
                  key: users
                  name: openldap
            - name: LDAP_PASSWORDS
              valueFrom:
                secretKeyRef:
                  key: passwords
                  name: openldap
            - name: LDAP_GROUP
              valueFrom:
                secretKeyRef:
                  key: group
                  name: openldap
          ports:
            - name: tcp-ldap
              containerPort: 1389
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: agent
spec:
  selector:
    matchLabels:
      app: agent
  serviceName: mpi
  replicas: 4
  template:
    metadata:
      labels:
        app: agent
        type: mpi-agent
    spec:
      subdomain: mpi
      # Use this to schedule exactly one worker
      # per node on your cluster...
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #           - agent
      #       topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs
        - name: openldap-login-public
          configMap:
            name: openldap-login-public
        - name: openldap-login-private
          configMap:
            name: openldap-login-private
            defaultMode: 0400
        - name: cgroup-volume
          hostPath:
            path: /sys/fs/cgroup
      containers:
      - image: jlphillips/openldap-login:2021-12-21
        name: mpi-agent
        volumeMounts:
          - name: nfs-volume
            mountPath: /home
          # - name: openldap-login-public
          #   mountPath: /etc/ldap.conf
          #   subPath: ldap.conf
          # - name: openldap-login-private
          #   mountPath: /etc/ldap.secret
          #   subPath: ldap.secret
          - name: openldap-login-private
            mountPath: /etc/munge/munge.key.tmp
            subPath: munge.key
          - name: openldap-login-public
            mountPath: /etc/slurm-llnl/slurm.conf
            subPath: slurm.conf
          - name: openldap-login-public
            mountPath: /etc/slurm-llnl/cgroup.conf
            subPath: cgroup.conf
          - name: cgroup-volume
            mountPath: /sys/fs/cgroup
        # resources:
        #   limits:
        #     memory: 8G
        securityContext:
          privileged: true
        imagePullPolicy: Always
      automountServiceAccountToken: false
      dnsConfig:
        searches:
          - mpi.hpc.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    app.kubernetes.io/name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scheduler
        type: mpi-agent
    spec:
      hostname: scheduler
      subdomain: mpi
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs
        - name: openldap-login-public
          configMap:
            name: openldap-login-public
        - name: openldap-login-private
          configMap:
            name: openldap-login-private
            defaultMode: 0400
        - name: cgroup-volume
          hostPath:
            path: /sys/fs/cgroup
      containers:
      - image: jlphillips/openldap-login:k8s
        name: mpi-agent
        volumeMounts:
          - name: nfs-volume
            mountPath: /home
          # - name: openldap-login-public
          #   mountPath: /etc/ldap.conf
          #   subPath: ldap.conf
          # - name: openldap-login-private
          #   mountPath: /etc/ldap.secret
          #   subPath: ldap.secret
          - name: openldap-login-private
            mountPath: /etc/munge/munge.key.tmp
            subPath: munge.key
          - name: openldap-login-public
            mountPath: /etc/slurm-llnl/slurm.conf
            subPath: slurm.conf
          - name: openldap-login-public
            mountPath: /etc/slurm-llnl/cgroup.conf
            subPath: cgroup.conf
          - name: cgroup-volume
            mountPath: /sys/fs/cgroup
        # resources:
        #   limits:
        #     memory: 8G
        securityContext:
          privileged: true
        imagePullPolicy: Always
      automountServiceAccountToken: false
      dnsConfig:
        searches:
          - mpi.hpc.svc.cluster.local
